# Hedgehog Configuration File

[project]
name = "test"
version = "0.1.0" # project version in semver
std = "0.1.0" # standard version in semver

[global]
color = true # enable or disable color in output

[build]
entry = "main.hhg" # entry point of the program/compiler
out-dir = "out" # output directory for build artifacts

mode = "debug" # debug | release

stage = "none" # stop after specified stage: none | lexer | parser | sem_an | mir-gen | code_gen | ext-build
debug-stage = "none" # debug specified stage: none | lexer | parser | sem_an | mir-gen | code_gen | ext-build

target = "auto" # cross-target triple: triple | auto
backend = "cpp" # backend format: cpp | qbe
incremental = false # incremental compilation (only with cpp backend)

warnings = "default" # warnings settings: default | all | none | pedantic
error-warnings = false # treat warnings as errors

[run]

args = [] # arguments to pass to program

[test]

test-dir = "test" # directory with test cases
list = false # list test cases without running them
fail-fast = false # stop on first failure
threads = -1 # number of threads to use (-1 => auto)
filter = "" # filter test cases (regex)

[clean]
mode = "all" # clean mode: all | build | gen

force = false # force clean without confirmation
dry-run = false # print files to be deleted without deleting them

[repl]
tmp-dir = "tmp" # temporary directory for repl
target = "auto" # cross-target triple: triple | auto
backend = "cpp" # backend format: cpp | qbe